repos:
-   repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
        - id: isort
    name: isort (python)
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
        - id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: flake8