name: test_and_build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, 3.10.9, 3.11]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip poetry
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
        poetry install

    - name: Check codestyle
      run: |
        poetry run pre-commit run --all-files

    - name: Run tests
      run: poetry run pytest tests

    - name: Build package
      run: poetry build
